### ISSUE TITLE
Required beans...

### ISSUE THREAD

**Issue by ghost** [choonchernlim/spring-security-adfs-saml2#12]
When I setup the basic configuration as you've described in the README, the application fails to start due to missing beans such as, SAMLAuthenticationProvider, MetadataManager, etc.   Doesn't your library configure all the required beans it and the saml-extension library needs?

**Comment by choonchernlim** [comment]
Yes it does. I know it works because I just configured one of my project apps to use it a few weeks ago. Can you please post your Spring security config and the actual error logs?

**Comment by ghost** [comment]
Ok. Thx.  Unfortunately, I was under a time crunch so had to go with a different solution and didn’t keep the configuration, but when I have time I’ll try it again.
