### ISSUE TITLE
Login failed action

### ISSUE THREAD

**Issue by timoteoponce** [choonchernlim/spring-security-adfs-saml2#6]
Great library, works like a charm.

Just wanted to know how can I configure a specific behavior/response when a 401 status or 
"AuthNResponse;FAILURE" is being sent from the server.

Note: setFailedLoginDefaultUrl didn't have any effect whatsoever, it just redirects to the ADFS login page.

**Comment by choonchernlim** [comment]
You may try to override `samlEntryPoint()`... for example, by default, Spring Security will do a redirect (302) to the login page when user is not authenticated. If I want it to throw 401 when user calls the web services (`/api/**`) and throw 302 on non `/api/**`, I can do something like this:-

```    
    @Override
    public SAMLEntryPoint samlEntryPoint() {
        SAMLEntryPoint samlEntryPoint = new SAMLEntryPoint() {
            @Override
            public void commence(final HttpServletRequest request,
                                 final HttpServletResponse response,
                                 final AuthenticationException e) throws IOException, ServletException {

                if (request.getRequestURI().startsWith(request.getContextPath() + "/api")) {
                    response.sendError(HttpServletResponse.SC_UNAUTHORIZED);
                }
                else {
                    super.commence(request, response, e);
                }
            }
        };

        samlEntryPoint.setDefaultProfileOptions(webSSOProfileOptions());

        return samlEntryPoint;
    }
```

**Comment by timoteoponce** [comment]
Freaking yes!!, this worked, thank you very much (y).

Keep on with the great work.
